# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/gather-goblin',
                'doc_host': 'https://eric-austin.github.io',
                'git_url': 'https://github.com/eric-austin/gather-goblin',
                'lib_path': 'gather_goblin'},
  'syms': {'gather_goblin.core': {'gather_goblin.core.foo': ('core.html#foo', 'gather_goblin/core.py')}}}
